name: portfolio
description: "juno's portfolio"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  ## logic
  flutter_bloc: ^9.1.1
  go_router: ^15.1.2

  ## ui
  flutter_icon_dialog: ^1.2.1
  smooth_page_indicator: ^1.1.0

  ## util
  image_picker: ^1.1.2
  url_launcher: ^6.2.5
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  copy_with_extension: ^6.0.1
  equatable: ^2.0.7
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  http_parser: ^4.0.2
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.9
  copy_with_extension_gen: ^6.0.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tpass/
    - assets/images/iwest/
    - assets/images/union/
    - assets/images/wikibox/
    - assets/images/isus/
